FROM quay.io/pipebug/java8

## install Logstash

ENV LOGSTASH_PACKAGE=logstash_1.5.3-1_all.deb \
    LOGSTASH_CONF=/etc/logstash/conf.d/

RUN curl -O https://download.elastic.co/logstash/logstash/packages/debian/${LOGSTASH_PACKAGE} && \
    dpkg -i ${LOGSTASH_PACKAGE} && \
    rm ${LOGSTASH_PACKAGE}

EXPOSE 5000

# cert/key
RUN mkdir -p /etc/pki/tls/certs && mkdir -p /etc/pki/tls/private
ADD logstash-forwarder.crt /etc/pki/tls/certs/logstash-forwarder.crt
ADD logstash-forwarder.key /etc/pki/tls/private/logstash-forwarder.key

ADD conf ${LOGSTASH_CONF}

CMD /opt/logstash/bin/logstash -f /etc/logstash/conf.d/ -vv